name: dependency_injection_flutter
description: A new Flutter project.
version: 0.0.1+1

environment:
  sdk: ">=2.8.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  built_collection: ^4.3.2
  built_value: ^7.0.9
  cupertino_icons: ^0.1.3
  http: ^0.12.0+4
  tuple: ^1.0.3

dev_dependencies:
  build_runner: ^1.8.0
  built_value_generator: ^7.0.9
  mockito: ^4.1.1
  pedantic: ^1.9.0
  test: ^1.14.1

flutter:
  uses-material-design: true
