name: dependency_injection_flutter
description: A new Flutter project.
version: 0.0.1+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  built_collection: ^4.3.2
  built_value: ^7.1.0
  http: ^0.12.1
  tuple: ^1.0.3

dev_dependencies:
  build_runner: ^1.9.0
  built_value_generator: ^7.1.0
  mockito: ^4.1.1
  pedantic: ^1.9.0
  test: ^1.14.3

flutter:
  uses-material-design: true
