name: dependency_injection_flutter
description: A new Flutter project.
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  built_collection: ^4.3.0
  built_value: ^7.0.0
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  tuple: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  built_value_generator: ^7.0.0
  mockito: ^4.1.1
  pedantic: ^1.8.0+1

flutter:
  uses-material-design: true